networks:
  laravel-net:

services:
  # Nginx (reverse-proxy + статические файлы)
  nginx:
    build: ./dockerfiles/nginx
    ports:
      - "${WEB_PORT-8080}:80"
    depends_on:
      - php
    volumes:
      - ./app:/var/www/html
    networks:
      - laravel-net

  # PHP-FPM + Composer
  php:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION:-8.3}"
    volumes:
      - ./app:/var/www/html
    env_file: .env
    networks:
      - laravel-net

  # СУБД
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD-root}"
      MYSQL_DATABASE:      "${DB_DATABASE-laravel}"
      MYSQL_USER:          "${DB_USERNAME-laravel}"
      MYSQL_PASSWORD:      "${DB_PASSWORD-secret}"
      TZ: Europe/Berlin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-net

volumes:
  mysql_data:
